import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../context/AuthContext";
import { TextSizeProvider } from "../context/TextSizeContext";
import SessionTimeoutWarning from "../components/SessionTimeoutWarning";
import TextSizeToggle from "../components/TextSizeToggle";
import TextSizeWrapper from "../components/TextSizeWrapper";
import ClientOnly from "../components/ClientOnly";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mi Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <AuthProvider>
          <TextSizeProvider>
            <TextSizeWrapper>
              {/* Contenido de la página */}
              <main className="min-h-screen">{children}</main>
              
              {/* Componente de advertencia de timeout */}
              <SessionTimeoutWarning />
              
              {/* Componente para cambiar tamaño del texto */}
              <ClientOnly>
                <TextSizeToggle />
              </ClientOnly>
            </TextSizeWrapper>
          </TextSizeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
